# Generated by Django 2.0.5 on 2018-06-13 11:51

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoplan',
            options={'verbose_name': 'Promo plan', 'verbose_name_plural': 'Promo Plans'},
        ),
        migrations.AddField(
            model_name='promolandingpage',
            name='CTA',
            field=models.CharField(default='Start Your Plan Now.', max_length=200),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.CharBlock(help_text='Content Below Headline')), ('screenshot', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
