# Generated by Django 2.0.5 on 2018-06-14 10:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0003_promolandingpage_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promolandingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('screenshot', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
    ]
