# Generated by Django 2.0.5 on 2018-06-14 16:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0005_auto_20180614_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promolandingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['h4', 'bold', 'italic', 'link', 'ol', 'ul'])), ('screenshot', wagtail.images.blocks.ImageChooserBlock(required=False)), ('highlight_color', wagtail.core.blocks.CharBlock())]))]),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='overview',
            field=wagtail.core.fields.StreamField([('fixed_width', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StreamBlock([('column_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', label='Two halves')), ('column_2_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', label='Two thirds/One third')), ('column_1_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))])), ('column_2', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common')), ('image', wagtail.images.blocks.ImageChooserBlock(group='Common'))]))], group='Columns', label='Three thirds'))]), icon='fa-th-large', label='Boxed'))], blank=True, null=True),
        ),
    ]
