# Generated by Django 2.0.5 on 2018-06-15 08:42

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0006_auto_20180614_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='promolandingpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['h4', 'bold', 'italic', 'link', 'ol', 'ul'])), ('screenshot', wagtail.images.blocks.ImageChooserBlock(required=False)), ('highlight_color', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], null=True))]))]),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='overview',
            field=wagtail.core.fields.StreamField([('freeform', wagtail.core.blocks.RichTextBlock()), ('two_three_column_grid', wagtail.core.blocks.StreamBlock([('column_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common'))]))], group='Columns', label='Two halves')), ('column_2_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common'))], max_num=1)), ('column_1', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common'))], max_num=1))], group='Columns', label='Two thirds/One third')), ('column_1_1_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common'))])), ('column_1', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common'))])), ('column_2', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.RichTextBlock(group='Common'))]))], group='Columns', label='Three thirds'))]))], blank=True, null=True),
        ),
    ]
