# Generated by Django 2.0.5 on 2018-06-15 14:49

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0007_auto_20180615_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='promolandingpage',
            name='benefits',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='body',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('feature_name', wagtail.core.blocks.CharBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('content', wagtail.core.blocks.RichTextBlock(features=['h4', 'bold', 'italic', 'link', 'ol', 'ul'])), ('screenshot', wagtail.images.blocks.ImageChooserBlock()), ('highlight_color', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], null=True)), ('feautre_icon', wagtail.images.blocks.ImageChooserBlock(help_text='For linking to the featured section')), ('slug', wagtail.core.blocks.CharBlock())]))]),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='hero_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promolandingpage',
            name='promo_duration',
            field=models.DateTimeField(blank=True, help_text='Set the time when you want this to expire.', null=True),
        ),
    ]
